config {
  type: "table",
  schema: "silver_egy",
  name: "silver_payment_transactions"
}

WITH
cleaned AS (
  SELECT
    TRIM(CAST(ccy AS STRING)) AS `currency`,
    TRIM(CAST(customer_code AS STRING)) AS `customer_id`,
    TRIM(CAST(mid AS STRING)) AS `merchant_id`,
    TRIM(CAST(payment_id AS STRING)) AS `payment_id`,
    ROUND(SAFE_CAST(payment_value AS NUMERIC), 2) AS `txn_amount`,
    TRIM(CAST(payment_status AS STRING)) AS `txn_status`,
    SAFE_CAST(created_dt AS TIMESTAMP) AS `txn_timestamp`,
    SAFE_CAST(last_update_dt AS TIMESTAMP) AS `updated_at`,
    'EGY' AS `_source_region`,
    'SQL_SERVER_EGY' AS `_source_system`,
    'bronze_egy.payment_transactions' AS `_source_table`,
    CURRENT_TIMESTAMP() AS `_processed_at`,
    CAST(NULL AS STRING) AS `_batch_id`
  FROM ${ref("bronze_egy", "payment_transactions")}
)
, ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY `payment_id`
      ORDER BY `updated_at` DESC
    ) AS `_row_number`
  FROM cleaned
)
SELECT
  `currency`,
  `customer_id`,
  `merchant_id`,
  `payment_id`,
  `txn_amount`,
  `txn_status`,
  `txn_timestamp`,
  `updated_at`,
  `_source_region`,
  `_source_system`,
  `_source_table`,
  `_processed_at`,
  `_batch_id`
FROM ranked
WHERE `_row_number` = 1
  AND `payment_id` IS NOT NULL
