config {
  type: "table",
  schema: "silver_ksa",
  name: "silver_txn_payments"
}

WITH
cleaned AS (
  SELECT
    TRIM(CAST(customer_id AS STRING)) AS `customer_id`,
    TRIM(CAST(payment_id AS STRING)) AS `payment_id`,
    ROUND(SAFE_CAST(amount AS NUMERIC), 2) AS `txn_amount`,
    SAFE_CAST(modified_date AS TIMESTAMP) AS `updated_at`,
    'KSA' AS `_source_region`,
    'SQL_SERVER_KSA' AS `_source_system`,
    'bronze_ksa.txn_payments' AS `_source_table`,
    CURRENT_TIMESTAMP() AS `_processed_at`,
    CAST(NULL AS STRING) AS `_batch_id`
  FROM ${ref("bronze_ksa", "txn_payments")}
)
, ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY `payment_id`
      ORDER BY `updated_at` DESC
    ) AS `_row_number`
  FROM cleaned
)
SELECT
  `customer_id`,
  `payment_id`,
  `txn_amount`,
  `updated_at`,
  `_source_region`,
  `_source_system`,
  `_source_table`,
  `_processed_at`,
  `_batch_id`
FROM ranked
WHERE `_row_number` = 1
  AND `payment_id` IS NOT NULL
