config {
  type: "table",
  schema: "silver_ksa",
  name: "silver_merchant_transactions"
}

WITH
cleaned AS (
  SELECT
    TRIM(CAST(currency AS STRING)) AS `currency`,
    TRIM(CAST(customer_id AS STRING)) AS `customer_id`,
    TRIM(CAST(merchant_id AS STRING)) AS `merchant_id`,
    ROUND(SAFE_CAST(transaction_amount AS NUMERIC), 2) AS `txn_amount`,
    TRIM(CAST(transaction_id AS STRING)) AS `txn_id`,
    TRIM(CAST(transaction_status AS STRING)) AS `txn_status`,
    SAFE_CAST(created_at AS TIMESTAMP) AS `txn_timestamp`,
    SAFE_CAST(updated_at AS TIMESTAMP) AS `updated_at`,
    'KSA' AS `_source_region`,
    'POSTGRES_KSA' AS `_source_system`,
    'bronze_ksa.merchant_transactions' AS `_source_table`,
    CURRENT_TIMESTAMP() AS `_processed_at`,
    CAST(NULL AS STRING) AS `_batch_id`
  FROM ${ref("bronze_ksa", "merchant_transactions")}
)
, ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY `txn_id`
      ORDER BY `updated_at` DESC
    ) AS `_row_number`
  FROM cleaned
)
SELECT
  `currency`,
  `customer_id`,
  `merchant_id`,
  `txn_amount`,
  `txn_id`,
  `txn_status`,
  `txn_timestamp`,
  `updated_at`,
  `_source_region`,
  `_source_system`,
  `_source_table`,
  `_processed_at`,
  `_batch_id`
FROM ranked
WHERE `_row_number` = 1
  AND `txn_id` IS NOT NULL
